# Generated by Django 4.2.16 on 2026-10-01 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(help_text='Например: Опрос по качеству преподавания за осенний семестр 2024/2025', max_length=255, verbose_name='Название анкеты')),
                ('description', models.TextField(blank=True, default='', help_text='Пояснение для студентов о целях опроса и гарантиях анонимности', verbose_name='Описание и инструкция')),
                ('academic_year', models.CharField(default='2024-2025', max_length=20, verbose_name='Учебный год')),
                ('semester', models.CharField(default='2024-1', max_length=20, verbose_name='Семестр')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна для прохождения')),
            ],
            options={
                'verbose_name': 'Шаблон анкеты',
                'verbose_name_plural': 'Шаблоны анкет',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('semester', models.CharField(default='2024-1', max_length=20, verbose_name='Семестр')),
                ('category', models.CharField(blank=True, default='', max_length=50, verbose_name='Категория проблемы')),
                ('source', models.CharField(choices=[('auto', 'Автоматически сформирована системой (Rule-Based)'), ('head', 'Вынесена заведующим кафедрой')], default='auto', max_length=20, verbose_name='Источник рекомендации')),
                ('recommendation_text', models.TextField(verbose_name='Текст рекомендации')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована'), ('reviewed', 'Принята к сведению')], default='published', max_length=20, verbose_name='Статус')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='workload.discipline', verbose_name='Дисциплина')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='workload.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Рекомендация преподавателю',
                'verbose_name_plural': 'Рекомендации преподавателям',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('clarity', 'Понятность и структурированность подачи материала'), ('fairness', 'Объективность и прозрачность системы оценивания'), ('relevance', 'Практическая ценность и актуальность содержания'), ('ethics', 'Педагогический такт, этика и контакт со студентами'), ('facilities', 'Организация учебного процесса и условия обучения'), ('general', 'Общие впечатления и пожелания')], default='clarity', max_length=50, verbose_name='Категория критерия')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('scale_5', 'Оценка по шкале (1–5 звезд)'), ('text', 'Текстовый отзыв в свободной форме')], default='scale_5', max_length=20, verbose_name='Тип вопроса')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок отображения')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.surveytemplate', verbose_name='Шаблон анкеты')),
            ],
            options={
                'verbose_name': 'Критерий / Вопрос анкеты',
                'verbose_name_plural': 'Критерии / Вопросы анкеты',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_open', models.BooleanField(default=True, verbose_name='Прием ответов открыт')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_assignments', to='workload.department', verbose_name='Кафедра')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_assignments', to='workload.discipline', verbose_name='Дисциплина')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_assignments', to='workload.studygroup', verbose_name='Учебная группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_assignments', to='workload.teacher', verbose_name='Преподаватель')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='surveys.surveytemplate', verbose_name='Шаблон анкеты')),
            ],
            options={
                'verbose_name': 'Назначение анкеты',
                'verbose_name_plural': 'Назначения анкет',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Оценка по 5-балльной шкале Лайкерта', null=True, verbose_name='Балл (1–5)')),
                ('text_response', models.TextField(blank=True, null=True, verbose_name='Текстовый комментарий')),
                ('submission_hash', models.CharField(db_index=True, help_text='Случайный токен сессии для группировки ответов без привязки к личности', max_length=64, verbose_name='Хэш сессии отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyassignment', verbose_name='Назначение анкеты')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ студента',
                'verbose_name_plural': 'Ответы студентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
