# Generated by Django 4.2.16 on 2026-10-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='Список вариантов для single_choice и multiple_choice', verbose_name='Варианты ответов'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='question_type',
            field=models.CharField(choices=[('scale_5', 'Оценка по шкале (1–5 баллов)'), ('single_choice', 'Один вариант ответа'), ('multiple_choice', 'Несколько вариантов ответа'), ('text', 'Текстовый отзыв в свободной форме')], default='scale_5', max_length=20, verbose_name='Тип вопроса'),
        ),
    ]
