# Generated by Django 4.2.16 on 2026-09-29 14:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО студента')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email студента')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='workload.studygroup', verbose_name='Учебная группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('semester', models.CharField(help_text='Например: 2024-1, 2024-2', max_length=20, verbose_name='Семестр')),
                ('grade', models.FloatField(help_text='Числовая оценка от 2.0 (неуд) до 5.0 (отл)', validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Оценка')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата выставления')),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('excel', 'Импорт из Excel'), ('moodle', 'LMS Moodle'), ('mock', 'Тестовые данные (LMS Mock)')], default='manual', max_length=20, verbose_name='Источник данных')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='workload.discipline', verbose_name='Дисциплина')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.student', verbose_name='Студент')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_grades', to='workload.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['group'], name='student_group_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['full_name'], name='student_name_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'semester'], name='grade_student_sem_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['discipline', 'semester'], name='grade_disc_sem_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['grade'], name='grade_val_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['semester'], name='grade_semester_idx'),
        ),
    ]
