# Generated by Django 4.2.16 on 2026-09-29 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=200, verbose_name='Название кафедры')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код / аббревиатура кафедры')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=300, verbose_name='Название дисциплины')),
                ('code', models.CharField(help_text='Например: GIS-01, INF-02', max_length=50, unique=True, verbose_name='Код дисциплины')),
                ('total_hours', models.PositiveIntegerField(verbose_name='Всего часов по учебному плану')),
                ('lesson_type', models.CharField(choices=[('lecture', 'Лекция'), ('practice', 'Практика'), ('lab', 'Лабораторная работа')], default='lecture', max_length=20, verbose_name='Тип занятия')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Например: БПИ-22-1, ЭК-21', max_length=50, unique=True, verbose_name='Название группы')),
                ('direction_code', models.CharField(help_text='Например: 09.03.01, 38.03.01', max_length=20, verbose_name='Код направления подготовки')),
                ('direction_name', models.CharField(help_text='Например: Информатика и вычислительная техника, Экономика', max_length=200, verbose_name='Наименование направления подготовки')),
                ('course', models.PositiveSmallIntegerField(help_text='Курс обучения (1-6)', verbose_name='Номер курса')),
                ('year', models.PositiveSmallIntegerField(help_text='Например: 2022', verbose_name='Год поступления')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
                'ordering': ['course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО преподавателя')),
                ('position', models.CharField(help_text='Например: Профессор, Доцент, Старший преподаватель, Ассистент', max_length=100, verbose_name='Должность')),
                ('hours_limit', models.FloatField(default=900.0, help_text='Норма годовой учебной нагрузки (по умолчанию 900 часов)', verbose_name='Лимит часов в год')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='workload.department', verbose_name='Кафедра')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('hours_plan', models.PositiveIntegerField(verbose_name='Плановые часы')),
                ('hours_fact', models.PositiveIntegerField(default=0, verbose_name='Фактически проведенные часы')),
                ('semester', models.CharField(help_text='Формат: ГГГГ-N, например: 2024-1 (осенний) или 2024-2 (весенний)', max_length=20, verbose_name='Учебный семестр')),
                ('room', models.CharField(blank=True, default='', help_text='Например: 101, Акт. зал', max_length=50, verbose_name='Номер аудитории')),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], null=True, verbose_name='День недели')),
                ('lesson_number', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 пара (08:30 - 10:00)'), (2, '2 пара (10:10 - 11:40)'), (3, '3 пара (12:00 - 13:30)'), (4, '4 пара (13:40 - 15:10)'), (5, '5 пара (15:20 - 16:50)'), (6, '6 пара (17:00 - 18:30)'), (7, '7 пара (18:40 - 20:10)')], null=True, verbose_name='Номер пары')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workloads', to='workload.discipline', verbose_name='Дисциплина')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workloads', to='workload.studygroup', verbose_name='Учебная группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='workload.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Учебная нагрузка',
                'verbose_name_plural': 'Учебная нагрузка',
                'ordering': ['semester', 'day_of_week', 'lesson_number'],
            },
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['course'], name='group_course_idx'),
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['direction_code'], name='group_direction_idx'),
        ),
        migrations.AddIndex(
            model_name='discipline',
            index=models.Index(fields=['code'], name='disc_code_idx'),
        ),
        migrations.AddIndex(
            model_name='workload',
            index=models.Index(fields=['teacher', 'semester'], name='wl_teacher_sem_idx'),
        ),
        migrations.AddIndex(
            model_name='workload',
            index=models.Index(fields=['discipline', 'semester'], name='wl_disc_sem_idx'),
        ),
        migrations.AddIndex(
            model_name='workload',
            index=models.Index(fields=['group', 'semester'], name='wl_group_sem_idx'),
        ),
        migrations.AddIndex(
            model_name='workload',
            index=models.Index(fields=['semester', 'day_of_week', 'lesson_number'], name='wl_schedule_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['department'], name='teacher_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['full_name'], name='teacher_name_idx'),
        ),
    ]
