# Generated by Django 4.2.16 on 2026-09-29 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('action', models.CharField(choices=[('CREATE', 'Создание записи'), ('UPDATE', 'Изменение записи'), ('DELETE', 'Удаление записи'), ('LOGIN', 'Вход в систему'), ('IMPORT', 'Импорт данных'), ('EXPORT', 'Экспорт данных')], max_length=20, verbose_name='Тип действия')),
                ('table_name', models.CharField(help_text='Например: Workload, Grade, Student', max_length=100, verbose_name='Таблица / сущность')),
                ('object_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Идентификатор объекта')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Предыдущее состояние (JSON)')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Новое состояние (JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес клиента')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='audit_user_idx'), models.Index(fields=['action'], name='audit_action_idx'), models.Index(fields=['table_name'], name='audit_table_idx'), models.Index(fields=['created_at'], name='audit_date_idx')],
            },
        ),
    ]
